[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rocfoundry"
version = "0.1.0"
description = "RocFoundry command-line tools"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
rocfoundry = "cli.rocfoundry:main"
