name: Clamp CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  rocm-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rocm/dev:6.4.4-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache ROCm toolchain
        uses: actions/cache@v4
        with:
          path: /opt/rocm
          key: rocm-${{ runner.os }}-6.4.4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y ninja-build cmake

      - name: Configure Clamp
        run: |
          export PATH=/opt/rocm/bin:$PATH
          cmake -S clamp -B build -G Ninja -DCMAKE_PREFIX_PATH=/opt/rocm

      - name: Build Clamp
        run: |
          export PATH=/opt/rocm/bin:$PATH
          cmake --build build

      - name: Run Tests
        run: |
          export PATH=/opt/rocm/bin:$PATH
          ctest --test-dir build --output-on-failure
