name: Clamp Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/rocm/dev:6.4.4-ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up ROCm environment
        run: |
          echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
          echo "HIP_DIR=/opt/rocm/lib/cmake/hip" >> $GITHUB_ENV
          echo "rocblas_DIR=/opt/rocm/rocblas/lib/cmake/rocblas" >> $GITHUB_ENV
          export PATH=/opt/rocm/bin:$PATH

      - name: Install Python dependencies
        run: |
          python3 -m pip install --user PyYAML requests

      - name: Validate ROCm cache
        run: |
          status="ok"
          if ls images/*.tar.gz >/dev/null 2>&1; then
            for archive in images/*.tar.gz; do
              echo "Validating $archive"
              if ! gzip -t "$archive"; then
                echo "::warning::gzip validation failed for $archive"
                status="warn"
                continue
              fi
              sha=$(sha256sum "$archive" | awk '{print $1}')
              echo "$archive sha256=$sha"
              if command -v docker >/dev/null 2>&1; then
                if docker load -i "$archive"; then
                  echo "Loaded image: $(basename "$archive")"
                else
                  echo "::warning::docker load failed for $archive"
                  status="warn"
                fi
              else
                echo "::warning::Docker unavailable; skipping load for $archive"
                status="warn"
              fi
            done
          else
            echo "::warning::No cached ROCm images found."
            status="warn"
          fi

      - name: Show cached CI mode
        run: python3 -m rocforge_ci mode show

      - name: Smart bootstrap
        run: |
          python3 -m rocforge_ci smart-bootstrap || python3 -m rocforge_ci offline-bootstrap

      - name: Configure with CMake
        run: |
          cmake -B build -G Ninja \
            -DHIP_DIR=$HIP_DIR \
            -Drocblas_DIR=$rocblas_DIR \
            -DCMAKE_PREFIX_PATH="/opt/rocm" \
            -DROCM_SNAPSHOT_JSON=build/rocm_snapshot.json

      - name: Build Clamp
        run: cmake --build build --config Release

      - name: Run CTest validation
        working-directory: build
        run: |
          ctest --output-on-failure

      - name: Run Python tests
        run: |
          python3 -m unittest tests.cli.test_clamp_cli
          python3 -m unittest tests.clamp.test_clamp_extension
          python3 -m unittest tests.clamp.test_rocm_verifier
          python3 ci/tests/test_ci_mode.py

      - name: Export telemetry (optional)
        if: success()
        run: |
          if [ -d build/telemetry ]; then
            jq '.stability_score' build/telemetry/*.json || true
          else
            echo "No telemetry data exported."
          fi

      - name: Reset CI mode marker
        if: always()
        run: python3 -m rocforge_ci mode reset

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: clamp-telemetry
          path: |
            build/clamp_test
            build/telemetry/
          if-no-files-found: warn
